### ISSUE TITLE
Consider using ArraySegment<byte> for MessageRecord

### ISSUE THREAD

**Issue by Scooletz** [GetManta/manta#12]
Have you considered using an array segment for the MessageRecord.Payload? For MS SQL Server you could use an `.Offset` and `.Count` of the param to specify the value properly. This could enable user to possibly use `System.Buffers.ArrayPool` and skip allocations for the serialization altogether.

https://github.com/GetManta/manta/blob/e4486ab5eb99b7adfbc661052385eaa97e2e4b72/src/Manta/MessageRecord.cs#L18

**Comment by dario-l** [comment]
That's a good idea. Thanks for the tip.

PS
Sorry for my delay. That's something weird. I do not have any notification about this issue. :/
